// MORE THAN ONE THING TO SAY ABOUT A PLACE.
//
// The country panel had exactly one "Did you know", so the second time you
// opened a country it told you what it told you the first time, and the card
// stopped being worth reading. A "New fact" button needs a bank behind it.
//
// WHERE THE FACTS COME FROM, AND WHAT IS HONEST ABOUT IT
//
// Two sources, and the panel makes no distinction because the reader should not
// have to:
//
//   1. WRITTEN FACTS - this file, plus the one in countryData. Chosen to be the
//      thing somebody would actually repeat, not the opening line of an
//      encyclopedia entry. Stable claims only: nothing that changes with an
//      election, a league table or an exchange rate, because a fact that goes
//      stale in a card nobody is maintaining is worse than no card.
//
//   2. DERIVED FACTS - built in `factsFor` from data the app already holds
//      (size, population, currency, language, time zone) and phrased as
//      something you could tell somebody. They are what keeps a country with a
//      short written entry from running out after two taps.
//
// COVERAGE IS DELIBERATELY UNEVEN. The bank is deepest for the places this
// community actually travels to and lives in, and thinner for the rest. Fifteen
// hand-written facts each for two hundred countries would be three thousand
// claims that nobody could check, and the wrong ones would be indistinguishable
// from the right ones. Where a country has fewer, the button simply cycles what
// there is - and the derived facts mean that is never fewer than about six.
//
// Keyed by ISO 3166-1 alpha-2, like every other country table here.

export const FACT_BANK = {
  // -------------------------------------------------------------- Europe
  GB: [
    'It is the only country in the world that does not put its own name on its postage stamps.',
    'No point on the island of Great Britain is more than about 113 km from the sea.',
    'The London Underground is the oldest metro in the world, running since 1863.',
    'It has more Indian restaurants than India has of some Western chains, and chicken tikka masala was invented here.',
    'Loch Ness holds more fresh water than every lake in England and Wales combined.',
    'The shortest scheduled flight in the world runs between two Orkney islands and lasts under two minutes.',
    'Pubs must legally be able to serve tap water free of charge if they serve alcohol.',
    'York has a street called Whip-Ma-Whop-Ma-Gate that is barely 35 metres long.',
    'It has four countries, three legal systems and no single written constitution.',
    'The Severn estuary has the second largest tidal range on earth, over 14 metres.',
    'Motorway service stations are legally required to let you park free for two hours.',
    'The oldest surviving bottle of beer in the world was brewed here in 1875.',
    'Big Ben is the bell, not the tower. The tower is the Elizabeth Tower.',
    'Postboxes carry the cypher of whichever monarch reigned when they were installed.',
    'Swans on the Thames are counted each summer in a ceremony called swan upping.',
  ],
  IE: [
    'There are no snakes, and there never were: the sea rose before they could arrive.',
    'More people of Irish descent live outside the country than in it, by a factor of about fourteen.',
    'Halloween began here as Samhain, and turnips were carved before pumpkins were.',
    'The longest place name is Muckanaghederdauhaulia, in County Galway.',
    'Every hedge and ditch in the country is legally protected during nesting season.',
    'Guinness signed a 9,000-year lease on its Dublin brewery in 1759.',
    'The tricolour is green for the Gaelic tradition, orange for the Protestant one and white for peace between them.',
    'Newgrange is older than Stonehenge and the pyramids at Giza.',
    'It is the only country in the world whose national symbol is a musical instrument.',
    'The state harp faces the opposite way round to the one on a Guinness label.',
    'Dublin takes its name from dubh linn, meaning black pool.',
    'The Cliffs of Moher rise more than 200 metres straight out of the Atlantic.',
    'Saint Patrick was not Irish; he was born in Roman Britain and brought here as a slave.',
    'Irish coffee was invented at Foynes in County Limerick for cold transatlantic passengers.',
    'The Burren is a limestone plateau where Arctic and Mediterranean plants grow side by side.',
  ],
  PT: [
    'Roughly 6,000 kilometres of the Atlantic separate its mainland from its most distant island.',
    'It has the oldest fixed borders in Europe, essentially unchanged since 1297.',
    'Portuguese is spoken by more people than French, German or Italian.',
    'Lisbon is older than Rome by several centuries.',
    'The world produces about half of all its cork here, and the trees are harvested without being cut down.',
    'The 1755 Lisbon earthquake effectively founded the science of seismology.',
    'Its oldest bookshop, Bertrand in Lisbon, has been open since 1732.',
    'The Vasco da Gama bridge is over 12 km long and accounts for the curvature of the earth in its design.',
    'Fado, its national music, has UNESCO heritage status.',
    'The alliance with England, signed in 1386, is the oldest active treaty in the world.',
    'Painted azulejo tiles cover whole building fronts, a habit inherited from Moorish Iberia.',
    'The custard tart known as pastel de nata was first baked by monks at Belém.',
    'Surfers ride enormous waves at Nazaré, thrown up by a canyon in the seabed offshore.',
    'The Douro valley was mapped out as a wine region in 1756, the first anywhere to be demarcated.',
    'Students at Coimbra still wear long black capes, and their style of fado is sung by men.',
  ],
  ES: [
    'It has more bars per person than any other country in the European Union.',
    'The national anthem has no official words.',
    'Spanish is the world\'s second most spoken native language, after Mandarin.',
    'It is the second most mountainous country in Europe after Switzerland.',
    'La Tomatina in Buñol throws roughly 150,000 tomatoes in an hour.',
    'The Sagrada Família has been under construction since 1882.',
    'Spain has 15 national parks and more UNESCO sites than almost anywhere else.',
    'The world\'s oldest restaurant still running, Sobrino de Botín, opened in Madrid in 1725.',
    'It shares a border with Morocco, at Ceuta and Melilla.',
    'Lunch is often eaten at two in the afternoon and dinner rarely before nine.',
    'Many small shops still shut for a few hours in the middle of the afternoon.',
    'Flamenco comes from Andalusia and is on the UNESCO intangible heritage list.',
    'Bread rubbed with tomato, pan con tomate, counts as breakfast in Catalonia.',
    'Pilgrims have walked the Camino de Santiago for more than a thousand years.',
    'Twelve grapes are eaten at midnight on New Year\'s Eve, one for each chime.',
  ],
  FR: [
    'It is the most visited country in the world, by a wide margin.',
    'There are around 1,600 named cheeses.',
    'France has the most time zones of any country, twelve, because of its overseas territories.',
    'It was legal to marry a dead person, with presidential approval, and still is in rare cases.',
    'The Eiffel Tower grows about 15 cm taller in summer as the iron expands.',
    'A French law requires radio stations to play a minimum share of French-language music.',
    'The Louvre is the most visited museum on earth and was once a fortress.',
    'Mont Blanc is the highest mountain in western Europe at 4,806 m.',
    'The metric system was invented here in the 1790s.',
    'A baguette de tradition may legally contain only flour, water, salt and yeast.',
    'Any restaurant will bring a carafe of tap water free, and asking for one is normal.',
    'The Tour de France has been run almost every year since 1903, pausing only for the wars.',
    'The number of kisses in a greeting changes from two to four depending on the region.',
    'Chamonix, under Mont Blanc, hosted the first Winter Olympics in 1924.',
    'Sparkling wine may only be called champagne if it was made in the Champagne region.',
  ],
  IT: [
    'It has more UNESCO World Heritage sites than any other country.',
    'Two entire countries sit inside it: San Marino and Vatican City.',
    'Italy did not exist as one country until 1861.',
    'The Colosseum could be emptied of 50,000 people in about fifteen minutes.',
    'Espresso is legally price-capped at the bar in Naples by long custom, not law.',
    'Its longest river, the Po, is only 652 km.',
    'Venice is built on millions of wooden piles driven into the lagoon bed.',
    'Pasta shapes number well over 350, and using the wrong one for a sauce is a real argument.',
    'Cappuccino after a meal is thought odd; espresso is the coffee you drink after dinner.',
    'The tower at Pisa began leaning while it was still being built.',
    'Three volcanoes on Italian soil are active: Etna, Stromboli and Vesuvius.',
    'Tomatoes only reached Italian kitchens after they were carried back from the Americas.',
    'Tipping is light because a cover charge, the coperto, is usually added instead.',
    'Coins thrown into the Trevi Fountain are collected daily and given to charity.',
    'Bologna has been teaching students since 1088, the oldest university in Europe.',
  ],
  DE: [
    'There is no federal speed limit on around half the autobahn network.',
    'It has over 1,500 breweries and more than 5,000 kinds of beer.',
    'University tuition is free, including for most international students.',
    'Berlin has more bridges than Venice.',
    'It borders nine countries, more than any other in Europe apart from Russia and France.',
    'A third of the country is forest.',
    'The world\'s narrowest street, Spreuerhofstraße in Reutlingen, is 31 cm at its tightest.',
    'Escaping from prison is not a crime here: the law accepts the urge to be free.',
    'Shops are shut on Sundays almost everywhere, by law.',
    'Quiet hours mean no drilling, mowing or loud music in most residential blocks on a Sunday.',
    'You pay a deposit called Pfand on bottles and cans, and get it back at the machine.',
    'A purity rule written in 1516 still shapes how a great deal of German beer is brewed.',
    'The decorated indoor Christmas tree spread to the rest of the world from Germany.',
    'Kindergarten, rucksack, doppelganger and angst are all words English simply took.',
    'The route of the Berlin Wall is marked in the city pavement with a double line of cobbles.',
  ],
  NL: [
    'About a quarter of the country sits below sea level.',
    'The Dutch are on average the tallest people in the world.',
    'There are more bicycles than people.',
    'It is the second largest exporter of food on earth, from a country the size of Maryland.',
    'The tulip crash of 1637 was the first recorded speculative bubble.',
    'Almost everyone speaks English, and it is not an official language.',
    'The Netherlands is one of twelve provinces; Holland is only two of them.',
    'Canal houses lean forward on purpose, with a hoist beam for lifting furniture through windows.',
    'Chocolate sprinkles, hagelslag, go on buttered bread at breakfast.',
    'At a birthday you congratulate everyone in the room, not only the person whose day it is.',
    'The country\'s name for itself, Nederland, simply means low country.',
    'Windmills were drainage machines long before they were postcards, pumping the polders dry.',
    'King\'s Day turns the whole country orange and lets anyone sell junk in the street for a day.',
    'The Afsluitdijk, a dam 32 km long, turned an arm of the sea into a freshwater lake.',
    'Delft blue pottery began as an attempt to imitate Chinese porcelain.',
  ],
  GR: [
    'No point in the country is more than about 137 km from the sea.',
    'It has around 6,000 islands, of which roughly 227 are inhabited.',
    'Greece produces more olive oil per person than anywhere else.',
    'The Greek language has been written continuously for over 3,000 years.',
    'Around 80 per cent of the country is mountainous.',
    'Nobody may be buried on Delos: the whole island is a protected sanctuary.',
    'Name days matter more than birthdays to many Greeks.',
    'Mount Athos is a self-governing monastic republic that women may not enter.',
    'The ancient Olympics were held at Olympia for around a thousand years before being abolished.',
    'Greeks say ne for yes, which sounds like no to almost every visitor.',
    'Feta has protected status and may only be made here, from sheep and goat milk.',
    'Santorini is the rim of a volcano that blew its own centre out in the Bronze Age.',
    'The Corinth Canal is so narrow that ships are towed through it.',
    'The frappé, an iced instant coffee, was invented at a Thessaloniki trade fair in 1957.',
    'Meteora has monasteries on rock pillars once reached only by rope ladder and net.',
  ],
  HR: [
    'The necktie began here, from the scarves of Croatian soldiers in the 17th century.',
    'It has 1,244 islands, islets and reefs, and about 50 are inhabited.',
    'The Dalmatian dog is named after Dalmatia.',
    'Zadar has a sea organ that the waves play through pipes in the steps.',
    'Its Plitvice lakes flow into each other over travertine barriers that are still growing.',
    'Dubrovnik\'s city walls run for nearly 2 km and can be walked the whole way round.',
    'The island of Korčula claims Marco Polo as a son, and shows you the house.',
    'There are eight national parks and eleven nature parks in a fairly small country.',
    'The emperor Diocletian built a palace at Split, and people still live inside its walls.',
    'Cravat Day is marked in Zagreb each October, in honour of the tie.',
    'White truffles are hunted with dogs in the oak woods of Istria.',
    'Hum, in Istria, bills itself as the smallest town in the world, with a few dozen residents.',
    'Zagreb has a museum devoted entirely to broken relationships.',
    'A wind called the bura drops off the mountains and can shut the coast road in minutes.',
    'Eduard Penkala patented an early mechanical pencil in Zagreb, and Croatians still say penkala.',
  ],
  IS: [
    'There are no mosquitoes.',
    'Almost all heating and electricity comes from geothermal and hydro power.',
    'Surnames are patronymic: children take a version of a parent\'s first name.',
    'It has no army, and never has.',
    'The parliament, the Althing, has met since 930 and is the world\'s oldest.',
    'Beer was illegal until 1989.',
    'There are no railways.',
    'The phone directory is alphabetised by first name, because surnames are not family names.',
    'A committee vets new first names to make sure they fit Icelandic grammar.',
    'Hot tap water smells faintly of sulphur because it comes straight out of the ground.',
    'Geothermal swimming pools are the social centre of almost every town.',
    'The island straddles two tectonic plates that are slowly pulling apart.',
    'Books are given on Christmas Eve and read that night, a custom called the jólabókaflóð.',
    'Belief in hidden people is strong enough that roads have occasionally been bent around rocks.',
    'The word geyser comes from Geysir, a hot spring in the south west.',
  ],
  NO: [
    'The coastline, with its fjords and islands, runs over 100,000 km.',
    'The sun does not set for weeks in the far north in summer.',
    'Norway gave London a Christmas tree every year since 1947 as thanks for the war.',
    'A penguin in Edinburgh Zoo holds the rank of Brigadier in the Norwegian Guard.',
    'Salmon sushi was a Norwegian marketing idea sold to Japan in the 1980s.',
    'The word ski is Norwegian, and cross-country skiing is treated as a national habit.',
    'Anything stronger than weak beer can only be bought from state shops called Vinmonopolet.',
    'Everyone\'s tax return is public and can be looked up.',
    'Lofoten lies above the Arctic Circle but stays ice free thanks to the Gulf Stream.',
    'Brown cheese, brunost, is boiled down from whey and tastes of caramel.',
    'The Atlantic Road hops between small islands on eight low bridges.',
    'Oil found under the North Sea in 1969 transformed the country\'s fortunes.',
    'The Sámi herd reindeer across the north and have their own parliament at Karasjok.',
    'Bergen sits among seven mountains and it rains there on most days of the year.',
    'Trolls turn up in place names, folk tales and on road signs warning of steep bends.',
  ],
  SE: [
    'There are nearly 270,000 islands, more than any other country.',
    'Allemansrätten gives everyone the right to walk and camp on almost any land.',
    'Sweden recycles so well it has imported rubbish to keep its plants running.',
    'The Icehotel in Jukkasjärvi is rebuilt from the river every winter.',
    'Fika, a coffee and a pastry with somebody, is close to a civic duty.',
    'Shoes come off at the door in almost every Swedish home.',
    'Midsummer means a flower crown, a maypole and a table of pickled herring.',
    'Sweden switched from driving on the left to the right overnight in 1967.',
    'Systembolaget, a state monopoly, is the only shop that sells stronger drink.',
    'The Nobel Prizes are handed over in Stockholm, all except the peace prize, which is Norwegian.',
    'Lagom, meaning just the right amount, is the closest thing to a national motto.',
    'The warship Vasa sank on her maiden voyage in 1628 and was raised almost intact in 1961.',
    'The country has stayed out of direct war since 1814.',
    'Semla buns are eaten before Lent, and a king is said to have died from eating too many.',
    'The town of Kiruna is being moved building by building because the mine beneath it is spreading.',
  ],
  DK: [
    'No point in Denmark is more than about 52 km from the sea.',
    'It has more bikes than cars, and Copenhagen has bike bridges.',
    'The Danish flag is the oldest continuously used national flag in the world.',
    'Lego is Danish, from "leg godt", meaning play well.',
    'Greenland and the Faroes are part of the Kingdom of Denmark.',
    'Hygge has no exact translation and covers candles, company and being comfortably indoors.',
    'Danish counts in twenties above forty, which even Swedes and Norwegians find strange.',
    'Tivoli Gardens opened in 1843 and gave Walt Disney ideas he took home.',
    'Almost every road in Copenhagen has a cycle track separated by its own kerb.',
    'The Little Mermaid statue is barely 1.25 m tall and surprises everyone who goes to see it.',
    'The country is a peninsula plus more than 400 islands, most of them empty.',
    'Danish pastry is called wienerbrød, Viennese bread, because Austrian bakers brought it.',
    'The bridge to Sweden turns into a tunnel halfway across, by way of an artificial island.',
    'Jante Law, an unwritten rule against thinking you are better than others, is still quoted.',
    'Bluetooth is named after a Danish king, and its symbol is his initials in runes.',
  ],
  FI: [
    'There are around 188,000 lakes and about 2.2 million saunas.',
    'It has the most forest cover of any country in Europe.',
    'Speeding fines are calculated from your income, and have run to six figures.',
    'Every newborn gets a state baby box that doubles as a cot.',
    'The Sámi languages are official in the north.',
    'Finns queue with a comfortable metre between them and mean nothing by it.',
    'The country holds championships in wife carrying, mobile phone throwing and swamp football.',
    'A silence in conversation is comfortable rather than awkward.',
    'Finnish has no future tense and no grammatical gender.',
    'Sisu, a stubborn kind of endurance, is the word Finns use to explain themselves.',
    'Lapland claims Santa Claus, and letters addressed to him arrive at Rovaniemi.',
    'Coffee breaks are written into Finnish collective employment agreements.',
    'Rye bread is dark, sour and eaten at almost every meal.',
    'Finland was part of Sweden for six centuries and then part of Russia for one.',
    'The northern lights are visible on many clear winter nights in the far north.',
  ],
  CH: [
    'It has four official languages: German, French, Italian and Romansh.',
    'Every household is within reach of a nuclear shelter by law.',
    'The country is legally neutral and last fought a foreign war in 1815.',
    'Its motorway tunnels total over 200 km.',
    'Citizens can force a national referendum with 100,000 signatures.',
    'Trains are timed to a clock-face pattern so connections repeat at the same minute every hour.',
    'There are roughly 1,500 lakes scattered across the country.',
    'Fondue has a rule: drop your bread in the pot and you buy the next round.',
    'Women only got the vote in national elections in 1971.',
    'The Alps cover about 60 per cent of the country, with the Jura and the plateau making up the rest.',
    'Swiss makers invented milk chocolate and the conching that gives it its smoothness.',
    'Emergency sirens are tested nationwide on the first Wednesday of February each year.',
    'The Pope\'s guard has been recruited from Switzerland since 1506.',
    'The Rhine, the Rhône and the Inn all rise in the Swiss Alps.',
    'Rubbish is paid for by buying official bags, so recycling costs nothing and throwing out does.',
  ],
  AT: [
    'The Vienna State Opera stages a different work almost every night of the season.',
    'Austria gave the world the croissant, by way of Vienna, before Paris did.',
    'Around 60 per cent of the country is in the Alps.',
    'Its national anthem was rewritten in 2012 to include daughters as well as sons.',
    'Viennese coffee houses are UNESCO listed, and you may sit for hours over a single cup.',
    'A glass of water is served with every coffee, and refilled without asking.',
    'Vienna has a cemetery holding around three million burials, more than the city has living residents.',
    'Mozart was born in Salzburg and left it as soon as he decently could.',
    'The Sound of Music is far better known abroad than it is in Austria.',
    'Many schools run a winter sports week where the whole class learns to ski.',
    'Austria ran an empire over much of central Europe until 1918.',
    'The Vienna Boys\' Choir has been singing since 1498.',
    'Freud saw his patients at Berggasse 19 in Vienna, now a museum.',
    'It is landlocked and shares a border with eight other countries.',
    'Only veal schnitzel may be sold as Wiener Schnitzel; anything else must be labelled differently.',
  ],
  PL: [
    'The Wieliczka salt mine has an entire cathedral carved out of salt.',
    'Warsaw\'s old town is a post-war reconstruction, rebuilt from paintings.',
    'Poland has the largest population of European bison in the world.',
    'Marie Curie was Polish, and named polonium after her country.',
    'Poland disappeared from the map for 123 years and reappeared in 1918.',
    'Białowieża is the last large piece of primeval forest left on the European plain.',
    'Pierogi are boiled dumplings with dozens of fillings, sweet as well as savoury.',
    'Name days are celebrated more warmly than birthdays.',
    'Copernicus was born in Toruń, a city that also keeps a museum of gingerbread.',
    'Vodka has been distilled here for centuries, and the word means little water.',
    'Christmas Eve dinner runs to twelve meatless dishes, with a place laid for an unexpected guest.',
    'Shifting dunes on the Baltic coast move several metres a year and bury the forest behind them.',
    'Kraków was the royal capital before Warsaw, and its old town came through the war intact.',
    'A trumpet call from St Mary\'s tower in Kraków breaks off mid-note, every hour, on the hour.',
    'Baltic amber is fossil tree resin millions of years old, and it fills the jewellery shops.',
  ],
  CZ: [
    'Czechs drink more beer per person than anyone else on earth.',
    'Prague Castle is the largest ancient castle complex in the world.',
    'The word "robot" was coined in a Czech play in 1920.',
    'There are more than 2,000 castles and châteaux in the country.',
    'Throwing officials out of a window, defenestration, happened twice in Prague and started wars.',
    'Czechia is the short name the country asked the world to start using in 2016.',
    'The Charles Bridge was begun in 1357 and carried all the traffic across the Vltava for centuries.',
    'Bohemian crystal has been blown and cut here since the Middle Ages.',
    'Pilsner was first brewed in Plzeň in 1842 and named the style most of the world now drinks.',
    'The astronomical clock in Prague has been keeping time since 1410.',
    'Mushroom picking in the woods is a national pastime with its own unwritten etiquette.',
    'The country is landlocked, whatever coast Shakespeare gave to Bohemia.',
    'Otto Wichterle spun the first soft contact lenses on a machine built from a toy construction set.',
    'The sugar cube was invented in the town of Dačice in 1843.',
    'Kafka lived in Prague all his life and wrote in German.',
  ],
  RO: [
    'The Palace of the Parliament in Bucharest is the heaviest building in the world.',
    'The Danube Delta is the largest and best preserved river delta in Europe.',
    'Romanian is a Romance language surrounded on all sides by Slavic ones.',
    'The Transfăgărășan road climbs to 2,042 m and is closed most of the year.',
    'Timișoara was the first city in mainland Europe lit by electric street lamps.',
    'Dracula was invented by an Irish novelist who never set foot in Transylvania.',
    'Bran Castle is sold as Dracula\'s castle although Vlad the Impaler barely used it.',
    'The Merry Cemetery at Săpânța has painted crosses carrying jokes about the dead.',
    'Some of the largest populations of brown bears and wolves in Europe live in these forests.',
    'Sarmale, cabbage rolls of minced meat and rice, appear at every celebration.',
    'The monasteries of Bucovina are painted with frescoes on the outside walls.',
    'The salt mine at Turda has been turned into an underground funfair.',
    'Romanian kept Latin words that the other Romance languages dropped centuries ago.',
    'The Carpathians curve through the middle of the country in a great arc.',
    'Villages in Maramureș still raise tall wooden churches and carve their gates.',
  ],
  HU: [
    'Budapest has more thermal springs than any other capital city.',
    'The Rubik\'s Cube was invented in Budapest in 1974.',
    'Hungarian is related to Finnish and Estonian, and to almost nothing else nearby.',
    'The Budapest metro line 1 is the oldest on mainland Europe, from 1896.',
    'Hungarians put the family name first, as in Bartók Béla.',
    'Goulash is a soup here, not the thick stew served under that name abroad.',
    'Paprika arrived from the Americas by way of the Ottomans and became the national spice.',
    'Buda and Pest were separate cities either side of the Danube until 1873.',
    'Tokaji sweet wine was drunk at royal courts and its vineyards were classified in 1737.',
    'The ballpoint pen was the work of László Bíró, a Hungarian journalist.',
    'Vitamin C was first isolated by Albert Szent-Györgyi, working with paprika.',
    'Lake Balaton is the largest lake in central Europe and freezes hard enough to walk on.',
    'The Chain Bridge, opened in 1849, was the first permanent crossing of the Danube here.',
    'Ruin bars occupy half-derelict buildings in Budapest\'s old Jewish quarter.',
    'Hungarians are reluctant to clink beer glasses, a habit traced back to 1849.',
  ],
  BE: [
    'Belgium once went 589 days without a government.',
    'It has more castles per square kilometre than any other country.',
    'The Brussels Grand-Place is carpeted with nearly a million begonias every other August.',
    'Voting is compulsory.',
    'Road signs change language at the regional border, and a town can have two names.',
    'Chips were probably invented here; they are fried twice and eaten with mayonnaise.',
    'Lambic beers are left open to the air and fermented by wild yeast.',
    'A beer may only be called Trappist if monks brew it inside their own abbey.',
    'The saxophone was invented by Adolphe Sax, born in Dinant.',
    'Brussels sprouts really are named after Brussels.',
    'Tintin, the Smurfs and Lucky Luke are Belgian, and comics are treated as an art form.',
    'The first steam railway on the European mainland ran from Brussels to Mechelen in 1835.',
    'The praline, a chocolate with a filled shell, was invented in Brussels in 1912.',
    'The Manneken Pis is a small bronze boy with a wardrobe of hundreds of costumes.',
    'Waterloo, where Napoleon was finally beaten, is just south of Brussels.',
  ],
  TR: [
    'Istanbul is the only city sitting on two continents.',
    'Tulips came to the Netherlands from the Ottoman Empire, not the other way round.',
    'Turkey has more ancient Greek ruins than Greece.',
    'Santa Claus, Saint Nicholas, was born in what is now Demre on the south coast.',
    'Turkish coffee is on the UNESCO intangible heritage list.',
    'The Grand Bazaar in Istanbul has around 4,000 shops along sixty covered streets.',
    'Tea is drunk all day from tulip-shaped glasses, and far more of it than coffee.',
    'The soft rock of Cappadocia was carved into houses, churches and whole underground cities.',
    'Turkish was written in Arabic script until the alphabet was changed in 1928.',
    'Hagia Sophia has been a church, a mosque and a museum.',
    'The white terraces at Pamukkale are calcium carbonate left behind by hot springs.',
    'The country sits on the North Anatolian fault and builds to strict earthquake codes.',
    'Turkish delight is called lokum, and rose is the traditional flavour.',
    'Mount Ararat, where tradition puts Noah\'s ark, stands in the far east.',
    'The Black Sea coast is the heartland of the world\'s hazelnut crop.',
  ],
  MA: [
    'Fez has the world\'s oldest continuously operating university, founded in 859.',
    'The medina of Fez is one of the largest car-free urban areas on earth.',
    'Morocco is one of the few countries with both Atlantic and Mediterranean coasts.',
    'Mint tea is poured from a height to aerate it, and refusing a glass is rude.',
    'Chefchaouen keeps its whole old town painted in shades of blue.',
    'Argan oil is pressed from nuts in the south west, largely by women\'s cooperatives.',
    'Goats climb the argan trees to get at the fruit.',
    'Oukaïmeden in the High Atlas is one of the few ski resorts in Africa.',
    'Couscous is traditionally eaten on Fridays after prayers.',
    'A tagine is both the stew and the conical clay pot it is cooked in.',
    'Jemaa el-Fnaa in Marrakesh turns into an open-air kitchen every evening.',
    'Morocco was the first country to recognise the independence of the United States, in 1777.',
    'Amazigh has its own script, Tifinagh, which appears on official signs.',
    'Haggling is expected in the souks, and paying the first price asked is unusual.',
    'The Hassan II Mosque in Casablanca was built partly out over the Atlantic.',
  ],
  // ------------------------------------------------------ Rest of the world
  US: [
    'It has no official language at federal level.',
    'Alaska has both the westernmost and easternmost points in the country, because it crosses the 180th meridian.',
    'The Library of Congress holds over 170 million items.',
    'There are more public libraries than McDonald\'s outlets.',
    'Yellowstone sits on top of an active supervolcano.',
    'The interstate system was built partly as a defence project.',
    'The Grand Canyon is over 1.6 km deep in places and cuts down to rock two billion years old.',
    'Alaska was bought from Russia in 1867 for about two cents an acre.',
    'Driving, drinking and marriage laws all change at the state line.',
    'Tipping is expected in restaurants because servers are paid a lower base wage.',
    'Route 66 was decommissioned in 1985 and is still signposted as a historic road.',
    'The Statue of Liberty was a gift from France and crossed the Atlantic in 350 pieces.',
    'Hawaii is the only state made entirely of islands, and it is still growing.',
    'Basketball was invented in Massachusetts in 1891, using two peach baskets.',
    'Post is still carried down into the Grand Canyon by mule, to a village at the bottom.',
  ],
  CA: [
    'It has more lakes than the rest of the world combined.',
    'The Canada-US border is the longest undefended border on earth.',
    'Canada has two official languages and about 70 Indigenous ones still spoken.',
    'The town of Churchill leaves cars unlocked so people can escape polar bears.',
    'Its coastline is the longest of any country, over 200,000 km.',
    'The Trans-Canada Highway runs about 7,800 km from the Atlantic to the Pacific.',
    'It takes roughly 40 litres of maple sap to boil down to one litre of syrup.',
    'Quebec runs on a civil law code inherited from France, unlike the rest of the country.',
    'Gravity is measurably weaker over Hudson Bay, a scar left by the last ice sheet.',
    'The Bay of Fundy has the largest tidal range on earth, over 16 metres.',
    'Tim Hortons was opened in 1964 by a hockey player and became a national fixture.',
    'Nunavut was created in 1999 and covers a fifth of the country.',
    'The name Canada comes from kanata, an Iroquoian word for village.',
    'Milk is sold in plastic bags in parts of eastern Canada.',
    'Several provinces have passed laws saying that an apology is not an admission of guilt.',
  ],
  MX: [
    'Mexico City is sinking by up to 50 cm a year.',
    'It gave the world chocolate, vanilla, tomatoes, chillies and maize.',
    'There are 68 recognised Indigenous languages with official status.',
    'The Chihuahua is the smallest dog breed and is named after a Mexican state.',
    'The Day of the Dead is a welcome rather than a mourning, with altars laid for those returning.',
    'The Aztec capital Tenochtitlan stood on an island in a lake that was later drained.',
    'At the equinox a shadow shaped like a snake slides down the pyramid at Chichén Itzá.',
    'Tequila may only be made from blue agave grown in a handful of designated regions.',
    'A mole sauce can run to dozens of ingredients, chocolate and chillies among them.',
    'The cenotes of Yucatán are flooded sinkholes linked by rivers running underground.',
    'Monarch butterflies fly thousands of kilometres to winter in fir forests west of the capital.',
    'The coat of arms shows an eagle on a cactus eating a snake, from an Aztec founding legend.',
    'An early colour television system was developed by a Mexican engineer, Guillermo González Camarena.',
    'Lucha libre wrestlers keep their masks on in public, and losing one is a serious business.',
    'The Baja California peninsula runs for more than 1,200 km down the Pacific side.',
  ],
  BR: [
    'Brazil borders every South American country except Chile and Ecuador.',
    'The Amazon produces a significant share of the world\'s oxygen from a single basin.',
    'It has won the football World Cup more times than any other country.',
    'Portuguese makes it the only Portuguese-speaking country in the Americas.',
    'Carnival fills Rio\'s Sambadrome with samba schools competing through the whole night.',
    'The Amazon carries more water to the sea than the next several largest rivers together.',
    'It is the only country crossed by both the equator and the Tropic of Capricorn.',
    'Brasília was built from nothing in the 1950s and laid out in the shape of an aeroplane.',
    'Feijoada, a black bean and pork stew, is eaten at lunch rather than in the evening.',
    'The Christ the Redeemer statue is struck by lightning several times a year.',
    'Capoeira, half martial art and half dance, was developed by enslaved Africans here.',
    'More uncontacted peoples live in Brazil than anywhere else on earth.',
    'The Iguaçu falls spread across hundreds of separate cascades on the Argentine border.',
    'São Paulo has the largest Japanese community outside Japan.',
    'Most Brazilian cars run on either petrol or sugarcane ethanol, whichever is in the tank.',
  ],
  AR: [
    'Ushuaia is the southernmost city in the world.',
    'Argentina has the highest and lowest points in the southern hemisphere.',
    'Tango was born in the port districts of Buenos Aires.',
    'The country consumes more beef per person than almost anywhere else.',
    'Yerba mate is shared from one gourd through a metal straw, and passing it has rules.',
    'Sitting down to dinner before ten at night counts as early.',
    'The Perito Moreno glacier advances rather than retreating, calving blocks into the lake.',
    'Buenos Aires claims the widest avenue in the world, up to sixteen lanes across.',
    'The Teatro Colón opera house in Buenos Aires opened in 1908 and is famous for its acoustics.',
    'Some of the largest dinosaurs ever found were dug out of Patagonia.',
    'Aconcagua, at 6,961 m, is the highest mountain outside Asia.',
    'Argentines use vos instead of tú, and their Spanish sounds Italian to other speakers.',
    'Dulce de leche goes into cakes, biscuits and the alfajores sold on every corner.',
    'The Iguazú falls plunge into a gorge called the Devil\'s Throat on the Brazilian border.',
    'Argentina claims a slice of Antarctica and keeps bases there all year round.',
  ],
  JP: [
    'There are more than 6,800 islands.',
    'Vending machines number roughly one for every 30 people.',
    'It has the oldest company in the world, a temple builder founded in 578.',
    'Trains apologise publicly for being a minute early.',
    'Around 73 per cent of the country is mountains.',
    'Slurping noodles is polite and shows you are enjoying them.',
    'Tipping is not expected and tends to cause confusion.',
    'Cherry blossom forecasts are broadcast like weather reports as the bloom moves north.',
    'Convenience stores sell concert tickets, fresh shirts and hot meals, around the clock.',
    'The shinkansen has run since 1964 and is famous for its safety record.',
    'Blood type is treated as a guide to personality the way star signs are elsewhere.',
    'Shoes come off at the door, and there is a second pair of slippers for the bathroom.',
    'Thousands of onsen, hot spring baths, are fed by the country\'s volcanoes.',
    'Mount Fuji is a volcano that last erupted in 1707 and is climbed by thousands each summer.',
    'Manhole covers are decorated with local designs and have their own collectors.',
  ],
  TH: [
    'It is the only country in Southeast Asia never colonised by a European power.',
    'The full ceremonial name of Bangkok is the longest place name in the world.',
    'The Thai calendar is 543 years ahead of the Gregorian one.',
    'Red Bull began as a Thai drink, Krating Daeng.',
    'The head is the most sacred part of the body and the feet the least.',
    'Pointing your feet at a person or a Buddha image is rude.',
    'The greeting is the wai, palms together, and how high you raise them depends on who you greet.',
    'Songkran, the new year in April, has turned into a nationwide water fight.',
    'Most Thai men spend a short period as a monk at some point in their lives.',
    'The tuk-tuk is descended from a Japanese three-wheeled delivery vehicle.',
    'Thailand means land of the free, and the country was called Siam until 1939.',
    'Spirit houses stand outside homes and shops to give displaced spirits somewhere to live.',
    'A Thai dish is built to balance sweet, sour, salty and spicy all at once.',
    'White elephants are royal by tradition and have to be presented to the king.',
    'Traffic drives on the left.',
  ],
  VN: [
    'It is the second largest coffee exporter in the world.',
    'Hanoi has a street where a train passes within inches of the cafés.',
    'Sơn Đoòng is the largest cave passage on earth, with its own jungle and clouds.',
    'The Vietnamese alphabet is Latin, adapted by Portuguese and French missionaries.',
    'Phở is eaten for breakfast far more often than for dinner.',
    'Motorbikes vastly outnumber cars, and crossing the road means walking slowly and steadily.',
    'Coffee is served with condensed milk because fresh milk was once hard to get.',
    'Bánh mì is a French baguette filled with entirely Vietnamese ingredients.',
    'Family names come first, and people are usually addressed by their given name.',
    'Hạ Long Bay holds around 1,600 limestone islands rising straight out of the water.',
    'Water puppetry is performed waist deep in a flooded stage, a tradition from the rice paddies.',
    'Vietnamese has six tones, so one syllable can carry six different meanings.',
    'The country runs over 1,600 km north to south but narrows to about 50 km at its waist.',
    'Tết, the lunar new year, empties the cities as everyone travels home.',
    'Fish sauce, nước mắm, is fermented in barrels and used the way salt is used elsewhere.',
  ],
  ID: [
    'It has over 17,000 islands, of which about 6,000 are inhabited.',
    'More than 700 languages are spoken here.',
    'It has more active volcanoes than any other country.',
    'The capital is moving from Jakarta to a new city on Borneo.',
    'The country spans three time zones and more than 5,000 km from end to end.',
    'Bali is largely Hindu in a country that is mostly Muslim.',
    'Komodo dragons live wild on only a handful of islands.',
    'Krakatoa erupted in 1883 and was heard thousands of kilometres away.',
    'Batik is drawn in hot wax before dyeing, and the craft is UNESCO listed.',
    'Borobudur is a ninth-century Buddhist monument built from around two million blocks of stone.',
    'Balinese rice terraces are watered through subak, a cooperative system run by temples.',
    'Orangutans live in the wild only on Borneo and Sumatra.',
    'The right hand is used for eating and giving, because the left is kept for washing.',
    'Nutmeg and cloves once grew only here, and empires fought wars over the islands that had them.',
    'The equator crosses the country, so the year splits into a wet season and a dry one.',
  ],
  IN: [
    'It has 22 official languages and hundreds more spoken.',
    'The Kumbh Mela is the largest gathering of people on earth.',
    'Chess, zero as a number and the decimal system all originated here.',
    'India has the world\'s largest postal network, including a floating post office.',
    'Cows wander through city traffic and everything goes around them.',
    'More than a thousand varieties of mango are grown, and the fruit is called the king of fruits.',
    'Indian Railways carries millions of passengers a day and has its own police force.',
    'A wobble of the head can mean yes, maybe, or simply that somebody is listening.',
    'The word shampoo comes from champo, meaning to press or massage the head.',
    'Big cricket matches empty the streets and fill every screen in the country.',
    'Holi is played by throwing coloured powder over anyone within reach.',
    'The Taj Mahal was built as a tomb for a wife and took over twenty years to finish.',
    'Vegetarianism is more widespread here than anywhere else on earth.',
    'The Ganges is treated as a goddess, and pilgrims bathe in it at dawn.',
    'Ladakh and Kerala can feel like different countries in climate, food and script.',
  ],
  AU: [
    'It is the only country that is also a continent.',
    'About 85 per cent of Australians live within 50 km of the coast.',
    'The Great Barrier Reef is the largest living structure on earth.',
    'Voting is compulsory, and not turning up brings a fine.',
    'It is wider east to west than the moon is across.',
    'Aboriginal Australians have the oldest continuing cultures on earth, going back tens of thousands of years.',
    'Uluru is a sandstone monolith that carries on for a long way underground.',
    'Most of the interior is arid, and Australians call all of it the outback.',
    'There are more kangaroos in the country than people.',
    'A rabbit-proof fence runs for thousands of kilometres across the west.',
    'The roof of the Sydney Opera House is covered in more than a million tiles.',
    'The continent drifts north by about seven centimetres a year, enough to shift its map coordinates.',
    'Vegemite is a salty yeast spread, scraped thinly on buttered toast and never eaten by the spoon.',
    'Christmas falls in midsummer, and lunch is often a barbecue on the beach.',
    'The Nullarbor carries the longest dead straight stretch of railway in the world, 478 km.',
  ],
  NZ: [
    'There are roughly five sheep for every person.',
    'It was the first country to give women the vote, in 1893.',
    'No part of the country is more than about 128 km from the sea.',
    'Its longest place name has 85 letters.',
    'The country has two official names, New Zealand and Aotearoa.',
    'There are no native land snakes, and very little else that can hurt you.',
    'A kiwi lays an egg that can weigh a fifth of the bird itself.',
    'Commercial bungee jumping started from a bridge outside Queenstown.',
    'The All Blacks perform a haka before every test match.',
    'The islands sit on the Pacific Ring of Fire and record thousands of earthquakes a year.',
    'It was the last large landmass on earth to be settled by people.',
    'Milford Sound is not a sound at all but a fiord, carved out by glaciers.',
    'The Southern Alps run down the spine of the South Island and are still rising.',
    'Hobbiton was built for the films near Matamata and left standing on a working farm.',
    'New Zealanders call themselves Kiwis after the bird, not the fruit.',
  ],
  ZA: [
    'It has three capital cities: Pretoria, Cape Town and Bloemfontein.',
    'There are 12 official languages, including sign language.',
    'Cape Town\'s Table Mountain is one of the oldest mountains on earth.',
    'It is the only country to have built nuclear weapons and then given them up.',
    'The first successful human heart transplant was carried out in Cape Town in 1967.',
    'The cloud that spills over Table Mountain is known locally as the tablecloth.',
    'The Cape floral region packs more plant species into a small area than almost anywhere.',
    'Vines have been planted at the Cape since the 1650s.',
    'The braai, a barbecue, has its own public holiday on Heritage Day.',
    'Kruger National Park is roughly the size of Wales.',
    'Lesotho sits entirely inside South Africa, surrounded on every side.',
    'The Big Five were named by hunters for the animals most dangerous to face on foot.',
    'Apartheid ended with the first fully democratic election in 1994.',
    'Trek, aardvark and meerkat all came into English from Afrikaans.',
    'Johannesburg grew out of a gold rush and still sits beside enormous mine dumps.',
  ],
  EG: [
    'The Great Pyramid was the tallest building in the world for around 3,800 years.',
    'Cleopatra lived closer in time to the moon landing than to the building of the pyramids.',
    'Almost the entire population lives on about 5 per cent of the land.',
    'Alexandria\'s library is being rebuilt as a modern one on the same site.',
    'The Nile flows north, which is why upper Egypt is in the south.',
    'The Aswan High Dam created Lake Nasser and put an end to the annual flood.',
    'Abu Simbel was cut into blocks and moved uphill to save it from the rising lake.',
    'Hieroglyphs were unreadable for centuries until the Rosetta Stone provided the key.',
    'The Suez Canal joins the Mediterranean to the Red Sea without a single lock.',
    'Ancient Egyptians played a board game called senet, and the boards survive in tombs.',
    'The everyday word for bread, aish, also means life.',
    'Cats were kept, mummified and mourned in ancient Egypt.',
    'The pyramids were built by paid labourers, whose villages and bakeries have been dug up.',
    'Sinai is the only part of the country that lies in Asia.',
    'Coptic, descended from ancient Egyptian, survives as a language of church services.',
  ],
  AE: [
    'Dubai\'s Burj Khalifa is so tall you can watch the sunset twice by taking the lift.',
    'The country was formed from seven emirates in 1971.',
    'Fewer than one in eight residents holds citizenship.',
    'The police fleet in Dubai includes a Bugatti.',
    'Abu Dhabi holds most of the country\'s land and most of its oil; Dubai has far less of both.',
    'An artificial archipelago off Dubai was built in the shape of a palm tree.',
    'Oil was only found in the 1950s; before that the coast lived on pearl diving.',
    'Camel races are run with robot jockeys, worked by owners driving alongside the track.',
    'Falconry is a national tradition, and a falcon can hold its own passport and fly in the cabin.',
    'Alcohol is sold through licensed hotels and shops rather than freely.',
    'Each emirate keeps its own ruler and a good deal of power at home.',
    'Outdoor work is banned during the middle of the day through the hottest weeks of summer.',
    'The Dubai metro runs without drivers.',
    'The dunes of the Empty Quarter, the Rub al Khali, reach into the south of the country.',
    'Road signs are written in Arabic and English almost everywhere.',
  ],
  KR: [
    'It has the fastest average internet speeds in the world.',
    'Everyone turns a year older at new year under the traditional age system.',
    'Seoul has more coffee shops per person than almost any city on earth.',
    'The DMZ has become an accidental nature reserve.',
    'Meals come with banchan, small shared side dishes that are refilled for free.',
    'Kimchi is buried in jars or kept in a fridge built for nothing else.',
    'Hangul, the alphabet, was designed in the 15th century to be quick to learn.',
    'The number four is avoided, and lifts often label that floor F instead.',
    'People are addressed by title rather than name, and age decides how you speak to someone.',
    'One transport card works on buses, the metro and taxis across the country.',
    'Food is delivered at any hour, including to parks and riverbanks.',
    'Military service is compulsory for men.',
    'Summer brings a rainy season called jangma.',
    'On Jeju island, the haenyeo are women who free dive for shellfish without air tanks.',
    'Writing a living person\'s name in red ink is avoided, as red is for the dead.',
  ],
  CN: [
    'It spans five geographic time zones but keeps one clock.',
    'The Great Wall is not one wall but many, built over roughly 2,000 years.',
    'Paper, printing, gunpowder and the compass were all invented here.',
    'It has the world\'s largest high-speed rail network by a long way.',
    'The written characters are shared across spoken varieties that cannot understand each other.',
    'More than fifty ethnic groups are officially recognised.',
    'Chopsticks are never stood upright in rice, because it looks like incense for the dead.',
    'Red is the colour of luck, and money is given at new year in red envelopes.',
    'Eight is a lucky number because it sounds like the word for wealth.',
    'Tea was drunk here for thousands of years before it ever reached Europe.',
    'Silk was a state secret, and smuggling silkworms out was punishable by death.',
    'The Grand Canal, begun well over a thousand years ago, is the longest artificial waterway on earth.',
    'Giant pandas in foreign zoos are on loan, and any cubs belong to China too.',
    'The new year holiday sets off the largest annual movement of people on the planet.',
    'The terracotta warriors were found by farmers digging a well in 1974.',
  ],
  PE: [
    'Peru has more than 4,000 varieties of potato.',
    'The Amazon river begins here.',
    'Machu Picchu was never found by the Spanish.',
    'Its northern desert holds the Nazca lines, only readable from the air.',
    'Ceviche is cured in lime juice and eaten at lunchtime, never in the evening.',
    'The Inca built thousands of kilometres of road without the wheel or any draught horse.',
    'Knotted cords called quipu were used to keep records in place of writing.',
    'Guinea pig, cuy, is a traditional dish in the Andes.',
    'Lake Titicaca has floating islands woven from reeds and rebuilt layer by layer.',
    'Lima sits in a coastal desert and gets almost no rain, only a grey mist called the garúa.',
    'The Colca canyon is deeper than the Grand Canyon and condors ride the thermals in it.',
    'Pisco sour is grape brandy, lime and egg white, and Chile disputes who invented it.',
    'Cusco was the Inca capital, and Spanish churches sit on Inca foundations that never moved.',
    'Coast, high Andes and Amazon rainforest all lie inside one country.',
    'Japanese and Chinese migration shaped the food, giving dishes like lomo saltado.',
  ],
  CO: [
    'Colombia is the second most biodiverse country on earth.',
    'It has coastline on both the Pacific and the Caribbean.',
    'Around 70 per cent of the world\'s emeralds come from here.',
    'Medellín has outdoor escalators built up the hillside barrios.',
    'The coffee-growing slopes of the central Andes have UNESCO status.',
    'Amazon rainforest, high Andes and Caribbean coast all sit inside the same country.',
    'Bogotá stands at about 2,600 m, and visitors feel it on the first day.',
    'The river at Caño Cristales turns red, yellow and green for part of the year, from a water plant.',
    'Vallenato is built around the accordion, brought to the Caribbean coast by German traders.',
    'Gabriel García Márquez set his fiction in a version of the Caribbean town he grew up in.',
    'Bogotá closes main roads to cars every Sunday for cyclists, runners and skaters.',
    'Small black coffees called tinto are drunk all day, from carts and thermos flasks.',
    'The salt cathedral at Zipaquirá is carved out of a working mine 180 m underground.',
    'More bird species live here than in any other country.',
    'Aguardiente, an anise spirit, is the traditional drink at any celebration.',
  ],
  CR: [
    'It abolished its army in 1948 and spent the money on schools.',
    'About 5 per cent of the world\'s known species live here.',
    'It runs on close to 100 per cent renewable electricity most years.',
    'Pura vida works as hello, goodbye and a way of saying life is going well.',
    'The country lies between two oceans and you can drive from one to the other in a day.',
    'Sloths move so slowly that algae grows in their fur.',
    'Costa Rica reversed its deforestation and put much of the country back under trees.',
    'There are more than 200 volcanic formations, several of them still active.',
    'Addresses are given in metres from a landmark rather than by street number.',
    'The Nicoya peninsula is one of the places where unusual numbers of people live past ninety.',
    'The quetzal, with tail feathers longer than its body, lives in the cloud forest.',
    'Costa Ricans call themselves Ticos, after a habit of ending words with tico.',
    'Sea turtles come ashore to nest in their thousands at once, in an arribada.',
    'Gallo pinto, rice and beans fried together, is breakfast.',
    'Parks and reserves cover roughly a quarter of the land.',
  ],
  KE: [
    'The Great Rift Valley is visible from space.',
    'Nairobi is the only capital city with a national park inside it.',
    'Kenya banned plastic bags with some of the strictest penalties anywhere.',
    'The equator crosses the country, and there are signs where the road cuts it.',
    'Wildebeest cross the Mara river in vast numbers each year on migration.',
    'Mount Kenya is an extinct volcano carrying glaciers almost on the equator.',
    'Mobile money pays for taxi fares, market vegetables and school fees.',
    'Ugali, a stiff maize porridge, is eaten by hand with stew.',
    'The country\'s distance runners come overwhelmingly from the highlands around Iten and Eldoret.',
    'Matatus, the shared minibuses, are painted, named and fitted with sound systems.',
    'Lake Turkana is the largest desert lake in the world.',
    'Some of the oldest human fossils ever found came out of the Rift Valley here.',
    'Tea is grown in the highlands and drunk as chai, boiled up with the milk.',
    'The Maasai are known for adumu, a dance judged on how high the men jump.',
    'The Indian Ocean coast has old Swahili towns of coral stone, such as Lamu.',
  ],
  TZ: [
    'Kilimanjaro is the highest free-standing mountain in the world.',
    'Around 38 per cent of the country is protected land.',
    'Swahili here is a first language for relatively few and a second for almost everyone.',
    'Zanzibar is semi-autonomous and has its own president.',
    'The carved doors of Stone Town are studded with brass spikes copied from Indian designs.',
    'Cloves grown on Zanzibar made the islands a centre of the spice trade.',
    'The Ngorongoro crater is a collapsed volcano with wildlife living inside it all year.',
    'Olduvai Gorge produced fossils that changed what we know about early humans.',
    'Lake Tanganyika is the second deepest lake in the world.',
    'The country was made in 1964 by joining Tanganyika and Zanzibar, which is where the name comes from.',
    'Nyama choma, grilled meat, is what an evening out is built around.',
    'Kilimanjaro can be walked up without ropes, though the altitude turns many people back.',
    'Serengeti comes from a Maasai word meaning endless plains.',
    'Dar es Salaam means house of peace.',
    'Tingatinga painting, bright enamel on board, began here in the 1960s.',
  ],
  NG: [
    'Nollywood produces more films a year than Hollywood.',
    'Over 500 languages are spoken.',
    'Lagos is one of the fastest growing cities in the world.',
    'There are more than 250 ethnic groups, of which Hausa, Yoruba and Igbo are the largest.',
    'Whose jollof rice is better is a long-running argument with Ghana.',
    'Fela Kuti invented Afrobeat here, and Afrobeats now travels the world.',
    'The river Niger gives the country its name, and its delta is one of the largest anywhere.',
    'A Yoruba name often carries a whole sentence of meaning.',
    'Lagos was the capital until Abuja was purpose-built and took over in 1991.',
    'Suya, spiced beef grilled on sticks, is sold from roadside grills after dark.',
    'The country runs from rainforest in the south to the edge of the Sahel in the north.',
    'The national football team is known as the Super Eagles.',
    'Nok terracotta sculptures made here are more than two thousand years old.',
    'Chinua Achebe\'s Things Fall Apart is among the most widely read of all African novels.',
    'Elders are greeted first, and in parts of the south younger people kneel or prostrate.',
  ],
  PH: [
    'It is made up of 7,641 islands.',
    'Filipinos send more text messages than almost anyone, earning it a "texting capital" nickname.',
    'The Chocolate Hills of Bohol are over a thousand near-identical mounds.',
    'Filipinos point with their lips rather than a finger.',
    'Christmas decorations go up in September and the season runs into January.',
    'Jeepneys began as wartime jeeps, stretched, decorated and used as shared buses.',
    'The rice terraces at Banaue were cut into the mountainside by hand over centuries.',
    'Centuries of Spanish rule left hundreds of Spanish words in everyday speech.',
    'Karaoke is a national pastime, with machines in homes and on street corners.',
    'The tarsier of Bohol is a primate small enough to sit in a palm, with enormous eyes.',
    'Balut, a boiled fertilised duck egg, is sold as a street snack.',
    'Around twenty typhoons cross or brush the islands in a typical year.',
    'Respect is shown by taking an elder\'s hand to your forehead, a gesture called mano.',
    'The country is named after a Spanish king, Philip II.',
    'Palawan has an underground river you can travel along by boat for several kilometres.',
  ],
  MY: [
    'The Petronas Towers were the tallest buildings in the world until 2004.',
    'Malaysian rainforest is around 130 million years old, older than the Amazon.',
    'It is split across two land masses either side of the South China Sea.',
    'Malay, Chinese and Indian traditions sit side by side, and the public holidays cover all of them.',
    'Durian is banned on trains and in many hotels because of the smell.',
    'Nasi lemak, coconut rice with sambal, is the national breakfast.',
    'Mount Kinabalu in Borneo rises to just over 4,095 m.',
    'The Batu Caves are reached by a long flight of brightly painted steps outside Kuala Lumpur.',
    'Rafflesia, the largest single flower in the world, grows here and smells of rotting meat.',
    'Nine states keep hereditary rulers, who take turns as king for five years each.',
    'Roti canai is flipped and stretched in the air before it hits the griddle.',
    'George Town on Penang has a UNESCO listed old quarter and a reputation for street food.',
    'Proboscis monkeys, with their heavy drooping noses, live only on Borneo.',
    'Malaysia was formed in 1963, and Singapore left it two years later.',
    'Teh tarik is pulled between two cups from a height to build a head of froth.',
  ],
  SG: [
    'It is one of only three surviving city-states.',
    'Chewing gum cannot be sold here.',
    'The country has grown roughly 25 per cent in land area by reclamation.',
    'Hawker culture, eating together at open-air food centres, is on the UNESCO heritage list.',
    'Littering, jaywalking and eating on the metro all carry fines.',
    'State-built flats house the large majority of residents.',
    'The Merlion, half lion and half fish, was designed for the tourist board in 1964.',
    'The name comes from Singapura, lion city, although lions never lived here.',
    'Wastewater is cleaned and sold back as drinking water under the name NEWater.',
    'The airport has an indoor waterfall and a butterfly garden.',
    'A car needs an expensive certificate before it can be registered, which keeps numbers down.',
    'Gardens by the Bay has metal supertrees that collect rainwater and solar energy.',
    'The island lies about 137 km north of the equator.',
    'National service is compulsory for male citizens.',
    'Durians are banned on the metro, with a sign showing the fruit crossed out.',
  ],
  IL: [
    'The Dead Sea is the lowest point on land on earth.',
    'It has more museums per person than any other country.',
    'Tel Aviv has the largest collection of Bauhaus buildings anywhere.',
    'The working week runs Sunday to Thursday, and much of the country closes for Shabbat.',
    'Hebrew was revived as an everyday spoken language after centuries of use only in prayer.',
    'The Dead Sea is salty enough that swimmers float without any effort.',
    'Jerusalem is holy to Judaism, Christianity and Islam.',
    'Kibbutzim were collective farms where property, meals and childcare were shared.',
    'Military service is compulsory for women as well as men.',
    'Hummus places often serve almost nothing else, and argue about who does it best.',
    'Much of the drinking water comes from desalinated seawater.',
    'Drip irrigation was developed here to grow crops in the desert.',
    'The cherry tomato was bred into its modern commercial form by Israeli scientists.',
    'Masada is a fortress on a desert plateau, reached by a path called the snake trail.',
    'The Sea of Galilee is a freshwater lake sitting well below sea level.',
  ],
  CL: [
    'It is about 4,300 km long and averages 180 km wide.',
    'The Atacama is the driest non-polar desert on earth.',
    'Chile has deserts, glaciers, rainforest and Pacific islands in one country.',
    'Easter Island belongs to Chile and lies more than 3,500 km out into the Pacific.',
    'The clear dry skies of the Atacama have drawn many of the world\'s largest telescopes.',
    'The strongest earthquake ever measured struck southern Chile in 1960.',
    'Chilean empanadas are baked and filled with beef, onion, an olive and a boiled egg.',
    'Pisco is claimed by both Chile and Peru, and the argument is taken seriously.',
    'Patagonian glaciers feed an ice field shared with Argentina.',
    'Chilean Spanish is spoken fast and drops its final consonants, which other speakers notice.',
    'Fruit is grown for northern winters, harvested when Europe cannot pick anything.',
    'Chile claims a wedge of Antarctica and keeps bases on it.',
    'Valparaíso is built on steep hills served by funicular lifts more than a century old.',
    'Copper mining shaped the country, and the pit at Chuquicamata is visible from far above.',
    'The monkey puzzle tree grows wild in Chilean forests and is protected there.',
  ],
  CU: [
    'Vintage American cars survive because imports were banned for decades.',
    'It has one of the highest literacy rates in the world.',
    'Cuba trains and exports more doctors than most far larger countries.',
    'The island runs about 1,250 km end to end and Cubans say it is shaped like a crocodile.',
    'Cigars are rolled by hand, and readers were once paid to read aloud to the rollers.',
    'Son, rumba and salsa all grew here out of Spanish and African roots.',
    'The Malecón, the seafront wall in Havana, doubles as the city\'s meeting place.',
    'A ration book has supplied households with basic food for decades.',
    'The Buena Vista Social Club brought older Cuban musicians back to the world\'s attention in 1997.',
    'Baseball, not football, is the national sport.',
    'Hemingway lived outside Havana for twenty years, and his house is kept as a museum.',
    'Guantánamo Bay is leased to the United States under a treaty signed in 1903.',
    'Cuban coffee is served short, strong and already sweetened.',
    'The Viñales valley has limestone hills called mogotes standing over tobacco fields.',
    'It is the largest island in the Caribbean.',
  ],
  JM: [
    'Jamaica has produced more world-record sprinters per person than anywhere.',
    'It was the first Caribbean country to gain independence, in 1962.',
    'Blue Mountain coffee grows above 900 m and is among the most expensive.',
    'Reggae grew out of ska and rocksteady in Kingston in the 1960s.',
    'Bob Marley\'s house on Hope Road in Kingston is now a museum.',
    'Jamaican Patois is an English-based creole built on West African grammar.',
    'Jerk cooking uses pimento wood smoke and scotch bonnet peppers.',
    'Ackee and saltfish is the national dish, and the fruit is poisonous until it opens on the tree.',
    'A Jamaican bobsleigh team qualified for the Winter Olympics in 1988.',
    'Rastafari began on the island in the 1930s.',
    'The Blue Mountains rise over 2,200 m within sight of the sea.',
    'Cars keep to the left, a habit left over from British rule.',
    'The name comes from Xaymaca, a Taíno word usually read as land of wood and water.',
    'Luminous Lagoon glows blue when the water is stirred, from the organisms living in it.',
    'Dunn\'s River Falls are climbed rather than admired, in a human chain.',
  ],
  NP: [
    'Eight of the world\'s ten highest mountains are here.',
    'The flag is the only national flag that is not a rectangle.',
    'Nepal has never been colonised.',
    'The clocks here run 45 minutes off the hour rather than on the hour or the half hour.',
    'Sherpa is an ethnic group, not a job title.',
    'The Kathmandu valley alone holds seven UNESCO listed monument zones.',
    'The Buddha was born at Lumbini, in what is now southern Nepal.',
    'The Nepali calendar runs about 57 years ahead of the Gregorian one.',
    'Namaste, palms together, is the everyday greeting.',
    'The lowland jungle in the south has tigers and rhinos, a world away from the peaks.',
    'Dal bhat, lentils and rice, is eaten twice a day by many Nepalis.',
    'Kathmandu has a living goddess, the Kumari, chosen as a young girl.',
    'Gurkha soldiers have served in the British and Indian armies since the 19th century.',
    'Cows are protected by law and wander through the streets.',
    'Prayer flags are printed with mantras and left to fade in the wind on purpose.',
  ],
  LK: [
    'It was called Ceylon until 1972, and the tea still is.',
    'Sri Lanka has the highest biodiversity density in Asia.',
    'Sigiriya is a palace built on top of a 200 m rock column.',
    'The island is shaped like a teardrop and sits just north of the equator.',
    'Adam\'s Peak is climbed overnight by pilgrims of four religions to reach a footprint at the top.',
    'Trains to the hill country run through tea estates on a line laid by the British.',
    'Wild elephants are given right of way and have corridors kept open between the parks.',
    'Rice and curry means half a dozen small dishes rather than one.',
    'True cinnamon comes from here and is a different species from the cassia sold elsewhere.',
    'Anuradhapura has a sacred fig grown from a cutting planted in the third century BC.',
    'Stilt fishermen sit on poles driven into the surf along the south coast.',
    'A tooth relic of the Buddha is kept at Kandy and paraded once a year by elephants.',
    'Blue whales and sperm whales gather in deep water off the southern coast.',
    'Two monsoons arrive from opposite directions, so it is always dry somewhere.',
    'Traffic drives on the left, another inheritance from British rule.',
  ],
  GE: [
    'Winemaking began here around 8,000 years ago.',
    'The Georgian alphabet is one of only fourteen scripts in the world.',
    'It has villages above 2,000 m that are cut off for months each winter.',
    'Wine is still fermented in clay vessels called qvevri, buried up to the neck in the ground.',
    'A Georgian feast, the supra, is run by a toastmaster called the tamada.',
    'Khachapuri is a cheese bread, and the Adjarian version arrives with an egg on top.',
    'Khinkali dumplings are held by the top knot, which is left on the plate.',
    'Georgians call their country Sakartvelo; the English name came from somewhere else entirely.',
    'The country lies between the Greater and Lesser Caucasus ranges.',
    'Tbilisi means warm place, after the sulphur springs it was founded on.',
    'Georgian polyphonic singing is on the UNESCO heritage list.',
    'In Svaneti, stone defensive towers stand attached to ordinary family houses.',
    'Stalin was born in Gori, where a museum to him still stands.',
    'Black Sea beaches and ski slopes are a few hours apart.',
    'A guest is a gift from God, according to a proverb everyone can quote.',
  ],
  AL: [
    'Nodding means no and shaking your head means yes.',
    'There are around 170,000 concrete bunkers left from the communist era.',
    'Albania has one of the highest rates of religious tolerance in Europe.',
    'Private cars were forbidden to ordinary citizens until 1991.',
    'Albanians call their country Shqipëria, usually translated as land of the eagles.',
    'Mother Teresa was of Albanian descent, and the airport is named after her.',
    'The Accursed Mountains in the north are crossed on foot between remote villages.',
    'A traditional code called the Kanun governed hospitality and blood feuds for centuries.',
    'Meeting for coffee is the default way of socialising, at almost any hour.',
    'The country has coast on both the Adriatic and the Ionian seas.',
    'Butrint is a Greek and Roman city now half swallowed by wetland.',
    'Berat is called the town of a thousand windows for its stacked Ottoman houses.',
    'Byrek, a layered savoury pastry, is sold in bakeries everywhere.',
    'Old Mercedes cars became a national favourite once the ban on private cars was lifted.',
    'The double-headed eagle on the flag comes from the seal of Skanderbeg.',
  ],
  ME: [
    'Montenegro means black mountain, after the dark pine forest on Mount Lovćen.',
    'The Bay of Kotor is often called Europe\'s southernmost fjord, though it is a submerged canyon.',
    'It uses the euro without being in the eurozone.',
    'Durmitor has glacial lakes that locals call mountain eyes.',
    'The Tara river canyon is the deepest in Europe, cut more than 1,300 m down.',
    'Kotor\'s old town is walled, with fortifications climbing the mountain behind it.',
    'Our Lady of the Rocks is an artificial island built up by sailors dropping stones for centuries.',
    'Sveti Stefan is a fortified islet joined to the shore by a narrow causeway.',
    'Men from these Dinaric mountains are among the tallest in the world.',
    'Montenegro voted to leave its union with Serbia in 2006, by a narrow margin.',
    'Ostrog monastery is built into a vertical cliff face.',
    'A bay, a canyon, high mountains and beaches all sit within a couple of hours of each other.',
    'Njegoš, a poet and prince-bishop, lies in a mausoleum on top of Lovćen.',
    'Cetinje, the old royal capital, is lined with the buildings of former foreign embassies.',
    'Njeguši ham is smoked in a village on the mountain road above Kotor.',
  ],
}

export default FACT_BANK
