// International dialling codes for the phone-number field.
//   iso2 - used to render the flag emoji (regional-indicator pair)
//   code - the dial code we store in profiles_private.phone_country (e.g. "+44")
//   name - shown in the dropdown
// Sorted roughly by likely use for a global travel-creator audience, then A-Z.
export const DIAL_CODES = [
  { iso2: 'GB', code: '+44', name: 'United Kingdom' },
  { iso2: 'IE', code: '+353', name: 'Ireland' },
  { iso2: 'US', code: '+1', name: 'United States' },
  { iso2: 'CA', code: '+1', name: 'Canada' },
  { iso2: 'AU', code: '+61', name: 'Australia' },
  { iso2: 'NZ', code: '+64', name: 'New Zealand' },
  { iso2: 'FR', code: '+33', name: 'France' },
  { iso2: 'DE', code: '+49', name: 'Germany' },
  { iso2: 'ES', code: '+34', name: 'Spain' },
  { iso2: 'PT', code: '+351', name: 'Portugal' },
  { iso2: 'IT', code: '+39', name: 'Italy' },
  { iso2: 'NL', code: '+31', name: 'Netherlands' },
  { iso2: 'BE', code: '+32', name: 'Belgium' },
  { iso2: 'CH', code: '+41', name: 'Switzerland' },
  { iso2: 'AT', code: '+43', name: 'Austria' },
  { iso2: 'PL', code: '+48', name: 'Poland' },
  { iso2: 'SE', code: '+46', name: 'Sweden' },
  { iso2: 'NO', code: '+47', name: 'Norway' },
  { iso2: 'DK', code: '+45', name: 'Denmark' },
  { iso2: 'FI', code: '+358', name: 'Finland' },
  { iso2: 'IS', code: '+354', name: 'Iceland' },
  { iso2: 'GR', code: '+30', name: 'Greece' },
  { iso2: 'CZ', code: '+420', name: 'Czechia' },
  { iso2: 'HU', code: '+36', name: 'Hungary' },
  { iso2: 'RO', code: '+40', name: 'Romania' },
  { iso2: 'HR', code: '+385', name: 'Croatia' },
  { iso2: 'UA', code: '+380', name: 'Ukraine' },
  { iso2: 'RU', code: '+7', name: 'Russia' },
  { iso2: 'TR', code: '+90', name: 'Turkey' },
  { iso2: 'IN', code: '+91', name: 'India' },
  { iso2: 'PK', code: '+92', name: 'Pakistan' },
  { iso2: 'BD', code: '+880', name: 'Bangladesh' },
  { iso2: 'CN', code: '+86', name: 'China' },
  { iso2: 'JP', code: '+81', name: 'Japan' },
  { iso2: 'KR', code: '+82', name: 'South Korea' },
  { iso2: 'TH', code: '+66', name: 'Thailand' },
  { iso2: 'VN', code: '+84', name: 'Vietnam' },
  { iso2: 'PH', code: '+63', name: 'Philippines' },
  { iso2: 'ID', code: '+62', name: 'Indonesia' },
  { iso2: 'MY', code: '+60', name: 'Malaysia' },
  { iso2: 'SG', code: '+65', name: 'Singapore' },
  { iso2: 'HK', code: '+852', name: 'Hong Kong' },
  { iso2: 'AE', code: '+971', name: 'United Arab Emirates' },
  { iso2: 'SA', code: '+966', name: 'Saudi Arabia' },
  { iso2: 'QA', code: '+974', name: 'Qatar' },
  { iso2: 'IL', code: '+972', name: 'Israel' },
  { iso2: 'ZA', code: '+27', name: 'South Africa' },
  { iso2: 'NG', code: '+234', name: 'Nigeria' },
  { iso2: 'KE', code: '+254', name: 'Kenya' },
  { iso2: 'EG', code: '+20', name: 'Egypt' },
  { iso2: 'MA', code: '+212', name: 'Morocco' },
  { iso2: 'GH', code: '+233', name: 'Ghana' },
  { iso2: 'BR', code: '+55', name: 'Brazil' },
  { iso2: 'AR', code: '+54', name: 'Argentina' },
  { iso2: 'MX', code: '+52', name: 'Mexico' },
  { iso2: 'CL', code: '+56', name: 'Chile' },
  { iso2: 'CO', code: '+57', name: 'Colombia' },
  { iso2: 'PE', code: '+51', name: 'Peru' },
  { iso2: 'BG', code: '+359', name: 'Bulgaria' },
  { iso2: 'RS', code: '+381', name: 'Serbia' },
  { iso2: 'SK', code: '+421', name: 'Slovakia' },
  { iso2: 'SI', code: '+386', name: 'Slovenia' },
  { iso2: 'LT', code: '+370', name: 'Lithuania' },
  { iso2: 'LV', code: '+371', name: 'Latvia' },
  { iso2: 'EE', code: '+372', name: 'Estonia' },
  { iso2: 'LU', code: '+352', name: 'Luxembourg' },
  { iso2: 'MT', code: '+356', name: 'Malta' },
  { iso2: 'CY', code: '+357', name: 'Cyprus' },
  { iso2: 'LK', code: '+94', name: 'Sri Lanka' },
  { iso2: 'NP', code: '+977', name: 'Nepal' },
  { iso2: 'TW', code: '+886', name: 'Taiwan' },
]

// Flag emoji from an ISO 3166-1 alpha-2 code (two regional-indicator letters).
export function flagEmoji(iso2) {
  if (!iso2) return ''
  return iso2
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
}
