// GENERATED by scripts/gen-world-airports.py - do not edit by hand.
//
// The content hash of public/geo/airports-world.json. lib/worldAirports
// appends it to the request so that regenerating the table busts every
// cache that holds the old one. See the note in the generator.
export const WORLD_AIRPORTS_VERSION = '80ebf2614ba1'
