import { useCallback, useEffect, useMemo, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { useCommunity } from '../../context/CommunityContext'
import { PageHeader, Skeleton, EmptyState, Spinner } from '../../components/ui'
import Icon from '../../components/Icon'
import { LOCALES, DEFAULT_LOCALE, bundledDict, getOverrides, loadLocale, setOverrides } from '../../lib/i18n'
import { listOverrides, saveOverride } from '../../lib/translations'
import { cx } from '../../lib/utils'
import { useT } from '../../lib/i18n'

// THE PLATFORM'S WORDS, EDITED BY THE PEOPLE WHO SPEAK THEM.
//
// Ethan: "can we have the ability for a country manager to edit this like an
// admin? If the Spanish country manager notices something wrong with the
// Spanish translations, there could be a section on the admin panel for
// languages, and they can edit the translation across the entire platform just
// for Spanish - or the language they selected if we have more languages in
// future. Would it just show all the copy? You could click on the pages, see
// all the copy there, and translate them rather than going through the
// platform, and it would immediately update. Build it so whenever we build
// future languages it's easy."
//
// THREE DECISIONS MAKE THIS SMALL, AND THEY ARE ALL DOWNSTREAM OF ONE THING:
// the dictionary is keyed on the ENGLISH SENTENCE (lib/i18n).
//
//  1. THERE IS NOTHING TO INVENT. A translator sees the English sentence and
//     types the Spanish one. No key names, no ids, no context field - the key
//     IS the context, which is the whole reason this codebase does not have
//     `settings.account.title` anywhere in it.
//  2. THE SCREENS COME FOR FREE. `src/locales/catalogue.json` is generated by
//     `prebuild` from the same scan the i18n report uses, so "the Challenges
//     page" is a real list of the strings that page says. Nobody maintains it.
//  3. AN EDIT IS A ROW, NOT A DEPLOY. `public.translations` (migration 168) is
//     an override layer over the bundled file on the same keys, loaded at boot
//     and merged at lookup - so clearing a box falls back to the shipped word
//     rather than to nothing, and a language nobody has touched behaves exactly
//     as it does today.
//
// WHO CAN OPEN IT. A platform admin, and a manager of a market whose `language`
// is not English. The DATABASE decides what actually saves (the RLS policy
// calls `can_edit_locale`); this only decides what to draw, because a page that
// offers an edit the server will refuse is a worse experience than a page that
// says you cannot edit it.

// The catalogue is 40kB of English sentences. It is a dynamic import so it
// lands in this page's own chunk rather than in the shell every creator
// downloads - the same reasoning as the dictionary itself.
const loadCatalogue = () => import('../../locales/catalogue.json')

export default function AdminLanguages() {
  const tr = useT()
  const { user, isAdmin } = useAuth()
  const { communities, memberships, loading: ctxLoading } = useCommunity()

  // WHICH LANGUAGES THIS PERSON MAY EDIT. An admin gets every language the
  // product has; a manager gets the language of the markets they run, and only
  // if it is not English - there is nothing to translate English INTO.
  const editable = useMemo(() => {
    const codes = LOCALES.filter((l) => l.code !== DEFAULT_LOCALE).map((l) => l.code)
    if (isAdmin) return codes
    const managed = new Set(
      memberships.filter((m) => m.role === 'manager').map((m) => m.community_id),
    )
    const mine = new Set(
      communities.filter((c) => managed.has(c.id)).map((c) => c.language).filter(Boolean),
    )
    return codes.filter((c) => mine.has(c))
  }, [isAdmin, communities, memberships])

  const [locale, setLocaleChoice] = useState(null)
  useEffect(() => { if (!locale && editable.length) setLocaleChoice(editable[0]) }, [editable, locale])

  const [catalogue, setCatalogue] = useState(null)
  const [screen, setScreen] = useState(null)
  const [search, setSearch] = useState('')
  const [rows, setRows] = useState(null)      // source -> value, as stored
  const [dictReady, setDictReady] = useState(false)
  const [error, setError] = useState('')
  const [savingKey, setSavingKey] = useState(null)

  useEffect(() => { loadCatalogue().then((m) => setCatalogue(m.default)) }, [])

  // The bundled dictionary has to be in memory to show what a string currently
  // says - an English admin editing Spanish has never loaded es.js.
  useEffect(() => {
    if (!locale) return
    setDictReady(false)
    loadLocale(locale).then(() => setDictReady(true))
  }, [locale])

  const refresh = useCallback(async () => {
    if (!locale) return
    setRows(null)
    const { rows: got, error: err } = await listOverrides(locale)
    if (err) { setError(err); setRows({}); return }
    const map = {}
    for (const r of got) map[r.source] = r.value
    setRows(map)
    // The app itself follows the edit immediately, which is what "it would
    // immediately update" means for the person making it: switch to Spanish and
    // the change is already there.
    setOverrides(locale, map)
  }, [locale])
  useEffect(() => { refresh() }, [refresh])

  // EVERY SCREEN, PLUS THE STRINGS NO SCREEN CLAIMS.
  //
  // The catalogue is built by scanning for `tr('a literal')`, so it cannot see
  // a string drawn through a TABLE - `tr(link.label)` over the network link
  // list, the market names, the room labels, the game modes. Those are real
  // copy that a manager has to be able to fix, and without this bucket they
  // would be reachable only by search, by somebody who already knew they
  // existed. Anything in the shipped dictionary that no screen claims lands
  // here.
  const withExtras = useMemo(() => {
    if (!catalogue) return null
    const claimed = new Set(Object.values(catalogue).flat())
    const loose = Object.keys(bundledDict(locale) || {}).filter((k) => !claimed.has(k)).sort()
    return loose.length ? { ...catalogue, 'Everything else': loose } : catalogue
    // `dictReady` IS the dependency that matters and the lint cannot see it:
    // `bundledDict` reads a module-level cache, so this has to recompute when
    // the dictionary finishes loading or the bucket is permanently empty.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [catalogue, locale, dictReady])

  const screens = useMemo(() => (withExtras ? Object.keys(withExtras) : []), [withExtras])

  // Everything in view: one screen's strings, or every string matching a
  // search. Searching across the whole product is how somebody fixes a word
  // they saw once and cannot place.
  const shown = useMemo(() => {
    if (!withExtras) return []
    const q = search.trim().toLowerCase()
    if (q) {
      const all = new Set()
      for (const list of Object.values(withExtras)) for (const s of list) all.add(s)
      const dict = bundledDict(locale) || {}
      return [...all].filter((s) => s.toLowerCase().includes(q)
        || String(rows?.[s] ?? dict[s] ?? '').toLowerCase().includes(q)).sort().slice(0, 300)
    }
    return screen ? withExtras[screen] || [] : []
  }, [withExtras, screen, search, rows, locale])

  async function write(source, value) {
    setSavingKey(source)
    const { error: err } = await saveOverride(locale, source, value, user?.id)
    setSavingKey(null)
    if (err) { setError(err); return }
    setError('')
    const next = { ...(rows || {}) }
    if ((value || '').trim()) next[source] = value.trim()
    else delete next[source]
    setRows(next)
    setOverrides(locale, next)
  }

  if (ctxLoading) return <div className="page max-w-5xl"><Skeleton className="h-40 w-full" /></div>
  // A creator who manages nothing has no business here, and the RLS would
  // refuse every write anyway. Send them home rather than drawing a form that
  // cannot save.
  if (!editable.length) return <Navigate to="/home" replace />

  const dict = bundledDict(locale) || {}
  const overrides = rows ?? getOverrides(locale)
  const loading = !withExtras || !dictReady || rows === null

  // How much of one screen has a translation at all. It is the number that
  // makes this finishable: a list of 40 sentences with "31 of 40" over it is a
  // job; the same list with nothing over it is a wall.
  const doneOn = (name) => {
    const list = withExtras?.[name] || []
    const n = list.filter((s) => overrides[s] || dict[s]).length
    return { n, total: list.length }
  }

  return (
    <div className="page max-w-6xl">
      <PageHeader
        title={tr("Languages")}
        subtitle={tr("Every word the platform says, and what it says in your language. Changes are live for everyone as soon as you save.")}
      />

      {editable.length > 1 && (
        <div className="mb-6 flex flex-wrap gap-1.5 rounded-card border border-gray-100 bg-white p-1.5 shadow-card">
          {editable.map((code) => {
            const meta = LOCALES.find((l) => l.code === code)
            return (
              <button
                key={code}
                type="button"
                onClick={() => { setLocaleChoice(code); setScreen(null) }}
                aria-pressed={locale === code}
                className={cx(
                  'rounded-lg px-3 py-1.5 text-xs font-semibold transition-colors',
                  locale === code ? 'bg-brand text-white' : 'text-smoke hover:bg-cloud hover:text-ink',
                )}
              >
                {meta?.flag} {meta?.native || code}
              </button>
            )
          })}
        </div>
      )}

      {error && (
        <p className="mb-4 rounded-card border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>
      )}

      <div className="mb-5">
        <input
          type="search"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder={tr("Search every word on the platform…")}
          aria-label={tr("Search the copy")}
          className="input w-full"
        />
      </div>

      {loading ? (
        <div className="space-y-3">{Array.from({ length: 8 }).map((_, i) => <Skeleton key={i} className="h-14 w-full" />)}</div>
      ) : (
        <div className="grid gap-6 lg:grid-cols-[18rem_minmax(0,1fr)]">
          {/* THE SCREENS, WHICH IS WHAT MAKES THIS FINISHABLE. Ethan asked to
              "click on the pages and see all the copy there", and it is also
              the only order in which translating makes sense: a sentence is
              easy to translate when you can see the three around it. */}
          <nav className="max-h-[70vh] overflow-y-auto overscroll-contain rounded-card border border-gray-100 bg-white p-1.5 shadow-card lg:sticky lg:top-24" aria-label={tr("Screens")}>
            {screens.map((name) => {
              const { n, total } = doneOn(name)
              const complete = n === total
              return (
                <button
                  key={name}
                  type="button"
                  onClick={() => { setScreen(name); setSearch('') }}
                  aria-current={screen === name && !search ? 'true' : undefined}
                  className={cx(
                    'flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-[13px] transition-colors',
                    screen === name && !search ? 'bg-brand text-white' : 'text-smoke hover:bg-cloud hover:text-ink',
                  )}
                >
                  <span className="min-w-0 flex-1 truncate font-medium">{name}</span>
                  <span className={cx(
                    'shrink-0 text-[11px] tabular-nums',
                    screen === name && !search ? 'text-white/80' : complete ? 'text-green-600' : 'text-gray-400',
                  )}>
                    {n}/{total}
                  </span>
                </button>
              )
            })}
          </nav>

          <div>
            {!search && !screen ? (
              <EmptyState
                icon={<Icon name="book" className="h-7 w-7" />}
                title={tr("Pick a screen")}
                hint={tr("Every sentence that screen says is listed with a box to translate it. Or search above to find one word anywhere on the platform.")}
              />
            ) : shown.length === 0 ? (
              <EmptyState
                icon={<Icon name="magnifier" className="h-7 w-7" />}
                title={tr("Nothing matches that")}
                hint={tr("Try a shorter phrase, or pick a screen from the list.")}
              />
            ) : (
              <ul className="space-y-2">
                {shown.map((source) => (
                  <StringRow
                    key={source}
                    source={source}
                    bundled={dict[source] || ''}
                    override={overrides[source] || ''}
                    busy={savingKey === source}
                    onSave={(v) => write(source, v)}
                  />
                ))}
              </ul>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

// ONE STRING. The English above, the translation in the box, and a plain
// statement of where the current word came from - because "this is the shipped
// translation" and "this is one somebody typed here" are the two states a
// translator has to be able to tell apart before deciding whether to touch it.
function StringRow({ source, bundled, override, busy, onSave }) {
  const tr = useT()
  const current = override || bundled
  const [text, setText] = useState(current)
  // Follow the stored value, but never over something being typed: the row
  // re-renders when any OTHER row saves.
  const [dirty, setDirty] = useState(false)
  useEffect(() => { if (!dirty) setText(current) }, [current, dirty])

  const commit = () => {
    setDirty(false)
    if (text.trim() === (override || '')) return
    // Typing the bundled word back is not an override - it is agreeing with it,
    // and storing a row that says the same thing is a row somebody has to
    // maintain for nothing.
    onSave(text.trim() === bundled ? '' : text)
  }

  return (
    <li className={cx(
      'rounded-card border bg-white p-3.5 shadow-card transition-colors',
      override ? 'border-brand/25' : current ? 'border-gray-100' : 'border-dashed border-amber-300',
    )}>
      <p className="text-[13px] leading-snug text-ink">{source}</p>
      <div className="mt-2 flex items-center gap-2">
        <input
          value={text}
          onChange={(e) => { setDirty(true); setText(e.target.value) }}
          onBlur={commit}
          onKeyDown={(e) => { if (e.key === 'Enter') e.currentTarget.blur() }}
          placeholder={tr("Not translated yet")}
          className="input w-full !py-2 text-[13px]"
          aria-label={`Translation of: ${source}`}
        />
        {busy && <Spinner className="h-4 w-4 shrink-0 text-brand" />}
      </div>
      <p className="mt-1.5 flex flex-wrap items-center gap-x-2 gap-y-1 text-[11px] text-smoke">
        {override ? (
          <>
            <span className="font-semibold text-brand">{tr("Edited here")}</span>
            {bundled && (
              <button
                type="button"
                onClick={() => { setDirty(false); setText(bundled); onSave('') }}
                className="font-semibold text-smoke underline hover:text-ink"
              >
                {tr("Back to the shipped wording")}
              </button>
            )}
          </>
        ) : current ? (
          <span>{tr("The shipped translation")}</span>
        ) : (
          <span className="font-semibold text-amber-600">{tr("Still shows in English")}</span>
        )}
      </p>
    </li>
  )
}
